plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    
}

testing {
    suites {
        test {
            useJUnitJupiter('6.0.1')
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

def isLinux = System.getProperty('os.name').toLowerCase().contains('linux')
tasks.named('processResources') {
    if (!isLinux) {
        exclude 'natives/libaccesskit_x86_64.so'
    }
}

version = '0.1.0'
publishing {
    publications {
        release(MavenPublication) {
            from components.java

            artifactId = rootProject.name

            pom {
                licenses {
                    license {
                        name = 'MIT'
                        url = 'https://opensource.org/license/mit'
                        distribution = 'repo'
                    }
                }
            }
        }
    }
}

jar {
    from(project.rootProject.file('licenses')) {
        into 'META-INF/licenses'
    }
    from(project.rootProject.file('LICENSE.txt')) {
        into 'META-INF/licenses'
        rename { 'AccessKit4J_License.txt' }
    }
}

test {
    failOnNoDiscoveredTests = false
}

task runSample(type: JavaExec) {
    group = "Execution"
    description = "Test A11Y integration via sample program"
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'net.buildabrowser.ak4j.sample.MainTest'
}